### ISSUE TITLE
KAFKA - ACK - Ensure Delivery

### ISSUE THREAD

**Issue by 1bberto** [BEagle1984/silverback#101]
I'd like to know if there is any configuration to force a message to be replicated in all brokers when I publish a message.
I had an issue with my application past week because one of my brokers went down and I lost the messages that were being published.
Do I need to change my KafkaProducerConfig in order to avoid it ?

**Comment by BEagle1984** [comment]
Yes, `KafkaProducerConfig` is just a wrapper around the [`ProducerConfig`](https://docs.confluent.io/current/clients/confluent-kafka-dotnet/api/Confluent.Kafka.ProducerConfig.html) class of the underlying Confluent.Kafka library.

I guess what you are looking for is the [`Acks`](https://docs.confluent.io/current/clients/confluent-kafka-dotnet/api/Confluent.Kafka.ClientConfig.html#Confluent_Kafka_ClientConfig_Acks) property (that is of course mirrored in the [`KafkaProducerConfig`](https://github.com/BEagle1984/silverback/blob/v2.2.0/src/Silverback.Integration.Kafka/Messaging/Configuration/ConfluentClientConfigProxies.cs#L37)).

```csharp
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services
            .AddSilverback()
            .WithConnectionToMessageBroker(options => options
                .AddKafka());
    }

    public void Configure(BusConfigurator busConfigurator)
    {
        busConfigurator.Connect(endpoints => endpoints
            .AddOutbound<IIntegrationEvent>(
                new KafkaProducerEndpoint("order-events")
                {
                    Configuration = new KafkaProducerConfig
                    {
                        BootstrapServers = "PLAINTEXT://kafka:9092",
                        Acks = Confluent.Kafka.Acks.All
                    }
                }));
    }
}
```
