### ISSUE TITLE
Custom headers not sent when using DbOutboundWorker

### ISSUE THREAD

**Issue by ppx80** [BEagle1984/silverback#102]
Version 2.2.0
Looking at the db OutboundMessage table, I noticed that the custom headers (set using the annotation) of my messages were not serialized and therefore sent.
I fixed the problem by registering a default outbound worker and assigning it to my outbound endpoint.
I hope it is useful to fix the problem.

**Comment by BEagle1984** [comment]
Definitely a bug. I'm already working on it and it will be fixed in v3.0.0 (unless it gets urgent and in that case I'll port it back to 2.2, but I'd prefer to avoid the double work).

**Comment by BEagle1984** [comment]
Fixed in v3.0.0 (currently in beta).
