### ISSUE TITLE
Idempotent Outbound Endpoint registration

### ISSUE THREAD

**Issue by meggima** [BEagle1984/silverback#110]
When registering the same outbound endpoint multiple times in the same application (e.g. when using a feature slicing approach), a message is written multiple times when it is published to the bus. I would expect it to be written only once:

```
// In feature1
builder.AddDefaultKafkaOutbound<MessageClass>("topic1", _settings)

// In feature2
builder.AddDefaultKafkaOutbound<MessageClass>("topic1", _settings)

// In code
await _publisher.PublishAsync(new MessageClass()); // produces a message twice

```

It would be great to design the registration of outbound endpoints in a way that it prevents duplicate registrations of the same endpoint.

**Comment by BEagle1984** [comment]
Seems reasonable and I will therefore change the behavior according to your suggestion. Thank you!
