### ISSUE TITLE
Documentation of DeliveryReportFields

### ISSUE THREAD

**Issue by msallin** [BEagle1984/silverback#124]
The documentation of KafkaProducerEndpoint.Configuration.DeliveryReportFields looks like this.
    /// <summary>
    ///     A comma separated list of fields that may be optionally set in delivery reports. Disabling delivery
    ///     report fields that you do not require will improve maximum throughput and reduce memory usage. Allowed
    ///     values: key, value, timestamp, headers, all, none. default: all importance: low
    /// </summary>

But if I don't set the "status" an exception is thrown.

https://github.com/BEagle1984/silverback/blob/7538edd69016add685453ebd17cd47b98d0bc259/src/Silverback.Integration.Kafka/Messaging/Configuration/Kafka/KafkaProducerConfig.cs#L69

**Comment by BEagle1984** [comment]
It's on purpose, as a cross check. You have to explicitly set `ThrowIfNotAcknowledged` to `false` if you remove the status from the delivery report, because I wouldn't be able to properly perform the checks.
At least this is the reasoning behind it. Do you think it's wrong?

**Comment by msallin** [comment]
The documentation of the property doesn't state that there is a "status" which can be set.
This is why I was unaware that it exist and finally I had to check the Silverback source to see why I got the exception and what was expected.
Thus, I suggest to add the status to the summary-doc.

**Comment by BEagle1984** [comment]
Ah, now I get it. Those summaries are automatically imported from Confluent.Kafka, I don't feel like I can maintain them on my own and keep up with the changes they implement from release to release.
Is the exception understandable though?

**Comment by BEagle1984** [comment]
That specific summary is copied from here:
https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/Config_gen.cs#L896-L905

...and it also seems to be autogenerated, probably from the librdkafka docs.

**Comment by msallin** [comment]
Okay. But status is an official Kafka thing? Then I'm going to file an issue there or do a PR.

**Comment by BEagle1984** [comment]
Yes, it seems to be a possible value on their side. It's strange that it isn't documented but I reverse engineered their producer  and they will not return a status if _"status"_  is not in the list of fields.

https://github.com/confluentinc/confluent-kafka-dotnet/blob/v1.5.3/src/Confluent.Kafka/Producer.cs#L625
and
https://github.com/confluentinc/confluent-kafka-dotnet/blob/v1.5.3/src/Confluent.Kafka/Producer.cs#L252

**Comment by msallin** [comment]
> Ah, now I get it. Those summaries are automatically imported from Confluent.Kafka, I don't feel like I can maintain them on my own and keep up with the changes they implement from release to release.
> Is the exception understandable though?

The exception is fine. I just noticed a missing space ;) 
https://github.com/BEagle1984/silverback/pull/125
