### ISSUE TITLE
Handle properly messages when return type is IAsyncEnumerable<T>

### ISSUE THREAD

**Issue by igorgiovannini** [BEagle1984/silverback#149]
At the moment there isn't any IReturnValueHandler able to handle IAsyncEnumerable<T> as return type.

I'd like to have Silverback able to handle IAsyncEnumerable<T> too, since it already supports IEnumerable<T> today.

(Pull request is coming... 😉)

**Comment by BEagle1984** [comment]
Thank you! ❤️

**Comment by BEagle1984** [comment]
Fix

**Comment by BEagle1984** [comment]
Fixed in v3.6.0. Thank you again for the PR!
