### ISSUE TITLE
Is it possible to add subscribers on demand?

### ISSUE THREAD

**Issue by mateusnc** [BEagle1984/silverback#151]
Hi,

Searched all over the docs but could not find a way to add a subscriber after my app is running.

I know it's possible to add new consumers by resolving the broker like that:
```cs
            var broker = ServiceProvider.GetRequiredService<IBroker>();
            var endpoint = new KafkaConsumerEndpoint("test-topic")
            {
                Configuration = new KafkaConsumerConfig
                {
                    GroupId = "test-group",
                    BootstrapServers = "PLAINTEXT://tests"
                }
            };

            broker.AddConsumer(endpoint);
```

So, is it possible to add custom subscribers after silverback is built just like I can add new consumers?

Thanks in advance!

**Comment by BEagle1984** [comment]
No, it isn't possible since the mediator is based on `Microsoft.Extensions.DependencyInjection` and you cannot register new services after the `IServiceProvider` has been built.

You need to build your own proxy, that is, a single subscriber which you use to invoke the other dynamically added subscribers on your own.

I don't know if this is your use case but you also have to be careful when having multiple subscribers for a consumed message, since there's no mechanism to guarantee the consistency: one subscriber could fail, while the other would succeed, causing the message to be reprocessed (depending upon the error policy), thus potentially leading to a duplicated processing.

**Comment by msallin** [comment]
Depending on your use case it may be helpful to know that you can start and stop consumers. We expose this functionality using a web API.

```csharp
[ApiExplorerSettings(GroupName = ApiGroups.ManagementApi)]
[Route("management/[controller]")]
[ApiController]
public class ConsumersController : ControllerBase
{
    private readonly IBrokerCollection _brokerCollection;

    public ConsumersController(IBrokerCollection brokerCollection) => _brokerCollection = brokerCollection;

    /// <summary>
    ///     Get all consumers.
    /// </summary>
    /// <returns>All Consumers.</returns>
    [HttpGet]
    [Route("")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    public ConsumersResponse Get()
    {
        return new ConsumersResponse(_brokerCollection.SelectMany(b => b.Consumers));
    }

    /// <summary>
    ///     Disconnect all consumers.
    /// </summary>
    /// <returns>NoContent status code.</returns>
    [HttpPost]
    [Route("[action]")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesDefaultResponseType]
    public async Task<IActionResult> Disconnect()
    {
        foreach (IBroker broker in _brokerCollection)
        {
            foreach (IConsumer consumer in broker.Consumers)
            {
                await consumer.DisconnectAsync();
            }
        }

        return NoContent();
    }

    /// <summary>
    ///     Disconnect a specific consumer.
    /// </summary>
    /// <param name="id">The Id of Consumer.</param>
    /// <returns>NoContent or NotFound status code.</returns>
    [HttpPost]
    [Route("{id}/[action]")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesDefaultResponseType]
    public async Task<IActionResult> Disconnect(string id)
    {
        foreach (IBroker broker in _brokerCollection)
        {
            IConsumer? consumer = broker.Consumers.FirstOrDefault(consumer => consumer.Id.Value.Equals(id, StringComparison.OrdinalIgnoreCase));

            if (consumer == null)
            {
                continue;
            }

            await consumer.DisconnectAsync();
            return NoContent();
        }

        return NotFound();
    }

    /// <summary>
    ///     Connect all consumers.
    /// </summary>
    /// <returns>NoContent status code.</returns>
    [HttpPost]
    [Route("[action]")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesDefaultResponseType]
    public async Task<IActionResult> Connect()
    {
        foreach (IBroker broker in _brokerCollection)
        {
            foreach (IConsumer consumer in broker.Consumers)
            {
                await consumer.ConnectAsync();
            }
        }

        return NoContent();
    }

    /// <summary>
    ///     Connect a specific consumer.
    /// </summary>
    /// <param name="id">The Id of Consumer need to connect.</param>
    /// <returns>NoContent or NotFound status code.</returns>
    [HttpPost]
    [Route("{id}/[action]")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesDefaultResponseType]
    public async Task<IActionResult> Connect(string id)
    {
        foreach (IBroker broker in _brokerCollection)
        {
            IConsumer? consumer = broker.Consumers.FirstOrDefault(consumer => consumer.Id.Value.Equals(id, StringComparison.OrdinalIgnoreCase));

            if (consumer == null)
            {
                continue;
            }

            await consumer.ConnectAsync();
            return NoContent();
        }

        return NotFound();
    }
}
```

**Comment by mateusnc** [comment]
> Depending on your use case it may be helpful to know that you can start and stop consumers. We expose this functionality using a web API.
> 
> ```cs
> [ApiExplorerSettings(GroupName = ApiGroups.ManagementApi)]
> [Route("management/[controller]")]
> [ApiController]
> public class ConsumersController : ControllerBase
> {
>     private readonly IBrokerCollection _brokerCollection;
> 
>     public ConsumersController(IBrokerCollection brokerCollection) => _brokerCollection = brokerCollection;
> 
>     /// <summary>
>     ///     Get all consumers.
>     /// </summary>
>     /// <returns>All Consumers.</returns>
>     [HttpGet]
>     [Route("")]
>     [ProducesResponseType(StatusCodes.Status200OK)]
>     public ConsumersResponse Get()
>     {
>         return new ConsumersResponse(_brokerCollection.SelectMany(b => b.Consumers));
>     }
> 
>     /// <summary>
>     ///     Disconnect all consumers.
>     /// </summary>
>     /// <returns>NoContent status code.</returns>
>     [HttpPost]
>     [Route("[action]")]
>     [ProducesResponseType(StatusCodes.Status204NoContent)]
>     [ProducesDefaultResponseType]
>     public async Task<IActionResult> Disconnect()
>     {
>         foreach (IBroker broker in _brokerCollection)
>         {
>             foreach (IConsumer consumer in broker.Consumers)
>             {
>                 await consumer.DisconnectAsync();
>             }
>         }
> 
>         return NoContent();
>     }
> 
>     /// <summary>
>     ///     Disconnect a specific consumer.
>     /// </summary>
>     /// <param name="id">The Id of Consumer.</param>
>     /// <returns>NoContent or NotFound status code.</returns>
>     [HttpPost]
>     [Route("{id}/[action]")]
>     [ProducesResponseType(StatusCodes.Status204NoContent)]
>     [ProducesResponseType(StatusCodes.Status404NotFound)]
>     [ProducesDefaultResponseType]
>     public async Task<IActionResult> Disconnect(string id)
>     {
>         foreach (IBroker broker in _brokerCollection)
>         {
>             IConsumer? consumer = broker.Consumers.FirstOrDefault(consumer => consumer.Id.Value.Equals(id, StringComparison.OrdinalIgnoreCase));
> 
>             if (consumer == null)
>             {
>                 continue;
>             }
> 
>             await consumer.DisconnectAsync();
>             return NoContent();
>         }
> 
>         return NotFound();
>     }
> 
>     /// <summary>
>     ///     Connect all consumers.
>     /// </summary>
>     /// <returns>NoContent status code.</returns>
>     [HttpPost]
>     [Route("[action]")]
>     [ProducesResponseType(StatusCodes.Status204NoContent)]
>     [ProducesDefaultResponseType]
>     public async Task<IActionResult> Connect()
>     {
>         foreach (IBroker broker in _brokerCollection)
>         {
>             foreach (IConsumer consumer in broker.Consumers)
>             {
>                 await consumer.ConnectAsync();
>             }
>         }
> 
>         return NoContent();
>     }
> 
>     /// <summary>
>     ///     Connect a specific consumer.
>     /// </summary>
>     /// <param name="id">The Id of Consumer need to connect.</param>
>     /// <returns>NoContent or NotFound status code.</returns>
>     [HttpPost]
>     [Route("{id}/[action]")]
>     [ProducesResponseType(StatusCodes.Status204NoContent)]
>     [ProducesResponseType(StatusCodes.Status404NotFound)]
>     [ProducesDefaultResponseType]
>     public async Task<IActionResult> Connect(string id)
>     {
>         foreach (IBroker broker in _brokerCollection)
>         {
>             IConsumer? consumer = broker.Consumers.FirstOrDefault(consumer => consumer.Id.Value.Equals(id, StringComparison.OrdinalIgnoreCase));
> 
>             if (consumer == null)
>             {
>                 continue;
>             }
> 
>             await consumer.ConnectAsync();
>             return NoContent();
>         }
> 
>         return NotFound();
>     }
> }
> ```

That's similar to my approach @msallin but you also give me some insights, thanks!

Sorry about the delay guys, I'll close this 
issue as my use case can be solved using the consumer API.
