### ISSUE TITLE
RPC Support

### ISSUE THREAD

**Issue by zaksnet** [BEagle1984/silverback#153]
Hello!

Is there support for RPC calls with Silverback?

**Comment by BEagle1984** [comment]
Do you mean over the message broker? Like sending a message and synchronously waiting for a reply on another topic/queue?
If this is what you mean: no, silverback doesn’t support this out of the box. I personally believe that this is an antipattern and you shouldn’t try to use an asynchronous channel to achieve synchronous communication. I would just call a REST API or similar instead.
You can build it on top of silverback though.
________________________________
From: Zak Stam ***@***.***>
Sent: Saturday, December 25, 2021 2:22:32 PM
To: BEagle1984/silverback ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [BEagle1984/silverback] RPC Support (Issue #153)


Hello!

Is there support for RPC calls with Silverback?

**Comment by zaksnet** [comment]
I am actually using [MQTTNet](https://github.com/chkr1011/MQTTnet) framework which already has an extension library for [RPC](https://www.nuget.org/packages/MQTTnet.Extensions.Rpc/). I suppose i could use this along with Silverback but i never found this library very intuitive anyway and i was wondering if you have something similar out of the box. Thank you for the answer!

**Comment by BEagle1984** [comment]
Interesting and I see why it might be interesting for MQTT in some cases.

**Comment by zaksnet** [comment]
I happen to use MQTT for an application that does not belong to the IOT world and so 20% of the calls actually expect an answer. This is of course feasible with in other ways like using Rest API or even SignalR but mixing them all makes it hard to maintain. In my case i just use different channels for requests and for responses (makes it a bit simpler because i can stick to only using MQTT). ResponseTopic that comes with MQTT 5 is also an interesting choice which simplifies things a little. Anyway i am currently having a custom strategy for topic routing and i was thinking of transitioning to Silverback since you seem to have solved a lot of the trouble already! Great job, keep it up!
