### ISSUE TITLE
Throw exception if broker is unavailable

### ISSUE THREAD

**Issue by RomanOlegovich** [BEagle1984/silverback#166]
Hello, I will fill this repository with issues 😁
IPublusher doesn't throw exception despite Kafka is stopped, just stuck (_publisher.PublishAsync_). Is it possible to change this behaviour? May be change timeout...

**Comment by BEagle1984** [comment]
It does throw after the timeout elapses. See [MessageTimeoutMs](https://silverback-messaging.net/api/Silverback.Messaging.Configuration.Kafka.ConfluentProducerConfigProxy.html#Silverback_Messaging_Configuration_Kafka_ConfluentProducerConfigProxy_MessageTimeoutMs). There might be other settings you want to adjust. Have a look at the configuration and refer to Confluent.Kafka or librdkfakfa documentation for details (Silverback just used Confluent.Kafka under the hood).
