### ISSUE TITLE
OnOffsetsCommitted event handler not called when IsAutoCommitEnabled = false

### ISSUE THREAD

**Issue by matthewdavena** [BEagle1984/silverback#167]
Hi,
when I configure the Kafka consumer with IsAutoCommitEnabled = false, the OnOffsetsCommitted handler is not called.
Is this a bug or is it by design? I had assumed that the event would be raised for any commit mode, automatic or manual.

Thanks in advance,
Matteo

**Comment by BEagle1984** [comment]
You are right. The underlying Confluent.Kafka library doesn't call the handler if you are manually committing, but when using Silverback you would expect it to be called (since you aren't manually committing, Silverback is doing it).
I will implement that. Thanks!

**Comment by matthewdavena** [comment]
Thanks!

**Comment by BEagle1984** [comment]
Fixed in v3.7.2.
