### ISSUE TITLE
Can't use Silverback.Integration.Kafka.SchemaRegistry with Apache.Avro because of dependency on Confluent.SchemaRegistry.Serdes

### ISSUE THREAD

**Issue by MarkGriffiths95** [BEagle1984/silverback#179]
Silverback.Integration.Kafka.SchemaRegistry uses Confluent.SchemaRegistry.Serdes version 1.3.0 which is deprecated. Suggested Alternatives
[Confluent.SchemaRegistry.Serdes.Avro](https://www.nuget.org/packages/Confluent.SchemaRegistry.Serdes.Avro/)

Silverback.Integration.Kafka.SchemaRegistry is not compatible with any projects using the suggested alternative because including both references in the project results in ambiguous references that cant be resolved.

Changing Confluent.SchemaRegistry.Serdes -> Confluent.SchemaRegistry.Serdes.Avro resolves the issues.

**Comment by BEagle1984** [comment]
Just published [v4.1.0](https://silverback-messaging.net/releases.html#410) including your PR.

**Comment by MarkGriffiths95** [comment]
Thank you!
