### ISSUE TITLE
Docs: Configuration - sample does not work

### ISSUE THREAD

**Issue by msallin** [BEagle1984/silverback#24]
Hi Sergio

See https://beagle1984.github.io/silverback/docs/configuration/external
This part raised an exception because the IProducer should be resolved. IProducer is scoped and there is no scope.

"ErrorPolicies": [
          {
            "Type": "Retry",
            "MaxFailedAttempts": 5,
            "DelayIncrement": "00:00:30"
          },
          {
            "Type": "Move",
            "Endpoint": {
              "Type": "KafkaProducerEndpoint",
              "Name": "basket-failedmessages"
            }
          }
        ]

**Comment by BEagle1984** [comment]
Fixed in versione 0.9.0
