### ISSUE TITLE
Question: Why is HandleMessagesOfType<> necessary?

### ISSUE THREAD

**Issue by msallin** [BEagle1984/silverback#33]
I've the an contract first situation where we generate Poco types and distribute them as NuGet. The consumer as well as the producer relay on this NuGet. Thus, the Poco classes does not implement a Silverback specific interface nor inherit a type. This means, I've to register them using `HandleMessagesOfType<>`. 

Therefore, I need to define a serializer and additionally, I also need to register the type. I would have expected that a type "on the bus" will just get routed to any subscriber which expects this type as parameter in a method.

Can you explain why it is necessary to explicitly register those types?

**Comment by BEagle1984** [comment]
Ciao Marc
You are right, all types are forwarded to the subscribers and you don't need any extra configuration for that.
HandleMessagesOfType is needed to let silverback know that those types have to be automatically pushed into the bus, if a subscribed method returns an object of such type. See https://beagle1984.github.io/silverback/docs/quickstart/bus#return-new-messages-republishing.
If you don't want/need to republish them, you don't need to register anything.

**Comment by msallin** [comment]
Hmm.. Then I guess I do smth wrong, as my subscriber doesn't get invoked, if I don't register my type using HandleMessagesOfType. I'll setup a repro later today.

**Comment by BEagle1984** [comment]
That's very strange. As you can see such configuration is being used only by the ReturnValueHandlers: https://github.com/BEagle1984/silverback/search?utf8=%E2%9C%93&q=MessageTypes&type=

Weird!

**Comment by BEagle1984** [comment]
Oh-oh! Nevermind.
I think you may be right, actually. It's a bug introduced in the last version, I'm also gonna fix it ASAP.

**Comment by BEagle1984** [comment]
This was fixed (https://github.com/BEagle1984/silverback/commit/78bb2d996b095187bebb50bdac7381b6ee016a99) and will be included in v. 0.11.

**Comment by BEagle1984** [comment]
Fixed in version 0.11.0-rc1. There are some breaking changes that may or may not affect you, but it would be wonderful if you could give the new version a try.

**Comment by BEagle1984** [comment]
Version 0.11.0 will be named 1.0.0 instead

**Comment by BEagle1984** [comment]
Fixed in release 1.0.0.
