### ISSUE TITLE
Question: How to get metainformation for a message

### ISSUE THREAD

**Issue by msallin** [BEagle1984/silverback#35]
I need to know from which partition a consumed message is from. Is it somehow possible to get this information on ISubscriber level (e.g. enriching after deserialization)?

If not, it would also be possible to maintain a global list which tracks, which Ids are from which partition. Is there a hook which allows to do so?

**Comment by BEagle1984** [comment]
Ciao @msallin
This is actually quite easy and straightforward. You can subscribe to an IInboundMessage<YourMessageType> to get a wrapper object exposing endpoint, headers, offset, etc.

https://github.com/BEagle1984/silverback/blob/848de1020a18a227d1d70c80aad5c0e8cf46b741/src/Silverback.Integration/Messaging/Messages/IInboundMessage.cs 

I should have mention this in the docs, I'll update it.

**Comment by msallin** [comment]
Ty!
