### ISSUE TITLE
Each call to a publisher leads to construction of all registered ISubscriber

### ISSUE THREAD

**Issue by msallin** [BEagle1984/silverback#37]
When I call the Execute/Publish method of a Publisher, this will lead into a construction of every ISubscriber, which is registered at the DI container.

This results in a huge overhead, as this will do a lot of unnecessary HeapAllocations, which again results in GC Pressure. As GC collects come at a cost, this should be reduced.

**Comment by BEagle1984** [comment]
Currently working on it. It will be hopefully included in the next big release.

**Comment by BEagle1984** [comment]
Improved in release 1.0.0
