### ISSUE TITLE
"AddXySubscriber" as Extension of IServiceCollection

### ISSUE THREAD

**Issue by msallin** [BEagle1984/silverback#41]
With the newest version, AddXySubscriber has to be called on the ISilverbackBuilder. If I have correctly checked the code, this isn't necessary and those methods could also be extension methods of IServiceCollection. 

As I have different modules which are responsible to register their components, this forces me to pass the ISilverbackBuilder.

See e.g. https://github.com/baernhaeckt/Backend/blob/master/Backend.Core/Features/Awards/Registrar.cs

What is the reason for the decision to offer this extension method for ISilverbackBuilder?

**Comment by BEagle1984** [comment]
Ciao my friend
I just checked and there is no technical reason anymore...there was a reason for that at some point, but it's not necessary anymore as all configuration methods actually just act on the `IServiceCollection`.
I kept is like that to enforce a cleaner and more readable configuration, while making it easier for the developer to leverage the intellisense.
That being said I can easily add some extensions to the `IServiceCollection` directly. I actually didn't think about your case (I use a completely different approach to DI, relying mostly on conventions).

As a temporary workaround you can just register your types using the regular `IServiceCollection.AddScoped`. You just need to register them twice (once as `ISubscriber` and once as self):
```c#
services.AddScoped<ISubscriber, UserAwardsQueryQueryHandler>();
services.AddScoped<UserAwardsQueryQueryHandler>();
```

Or create a temporary extension method on your side;
```c#
public IServiceCollection AddScopedSubscriber<TSubscriber>(this IServiceCollection services)
    where TSubscriber : class, ISubscriber
{
    services.AddScoped<ISubscriber, TSubscriber>();
    services.AddScoped<TSubscriber>();
}
```

As said, I'll add the methods back (with all the necessary overloads) in the next patch release.

**Comment by BEagle1984** [comment]
The `Add*Subscriber` and `Add*Behavior` extension methods for `IServiceCollection` have been reintroduced in [Release 1.0.2](https://github.com/BEagle1984/silverback/releases/tag/1.0.2).
