### ISSUE TITLE
Provide a message 'replay' mechanism (offset reset to the beginning)

### ISSUE THREAD

**Issue by gitjosephbeer** [BEagle1984/silverback#57]
A required feature in conjunction with Kafka on my part is the possibility to reset a topic-offset to the very beginning (offset 0, and maybe additionally to a certain timestamp).

This would allow to 'replay' messages, regardless if they had been consumed before already (see https://medium.com/@psinghal04/replaying-kafka-messages-an-implementation-in-golang-e5c6867cf084).

Such a topic offset reset should be possible at initial topic assignement and as well after a revoke and reassignment (e.g. consumer scale up/down).

I could imagine, that the KafkaConsumerConfig.AutoOffsetReset feature could therefor be enhanced by a new option AutoOffsetReset.Beginning (or First/Zero/Bottom?).

And/or in the KafkaPartitionsAssignedEvent handler allow access to the consumers of the IBroker and then call Acknowledge(offsets).
IBroker already has a GetConsumer() method, but the Broker base implementation there always creates and adds a new one in any case. My Suggestion would be to either rename this one to AddConsumer() and provide a 'readonly' GetConsumer() method or change the GetConsumer() method to the similar as Broker.GetProducer(IEndpoint) method which internally uses a _producers dictionary and _producers.GetOrAdd().

**Comment by BEagle1984** [comment]
> I could imagine, that the KafkaConsumerConfig.AutoOffsetReset feature could therefor be enhanced by a new option AutoOffsetReset.Beginning (or First/Zero/Bottom?).

Well, no, this is a bit outside from out control here. The `AutoOffsetReset` mechanism is provided by Confluent/Kafka and is exposed as-is. It would be confusing and dangerous to extend it with new "virtual" strategies, like you propose.
Also, the meaning of `AutoOffsetReset` is to tell Kafka what to do when the consumer offset is unknown (brand new consumer group) but this isn't really the case we have here.

> And/or in the KafkaPartitionsAssignedEvent handler allow access to the consumers of the IBroker and then call Acknowledge(offsets).

Yes, this is the way to go and thank you very much for your pull request!
But as you noticed it isn't so straightforward and some tests are failing. Always resolving to a new consumer is not what Silverback expects and can potentially break many stuff (acknowledgements, etc.).
I'll think about a (hopefully) clean way to allow you to access the existing consumers without breaking the existing functionality. (Let's continue the discussion in the pull request.)

**Comment by BEagle1984** [comment]
It is now possible to subscribe to the `KafkaPartitionsAssignedEvent` and set the start offset for the assigned partitions. See https://beagle1984.github.io/silverback/docs/kafka/events#setting-starting-offsets-on-partitions-assignment.

This functionality is already available in the pre-release 2.0.0-rc1.
