### ISSUE TITLE
Improve functionality to do component integration testing

### ISSUE THREAD

**Issue by msallin** [BEagle1984/silverback#62]
It would be nice to have support for a full component integration test using the in memory broker. Currently the serialization isn't tested.

A consumer scenario where byte[] is the input for the test:
message (byte[]) --> message (string) --> message (deserialized) --> ISubscriber (assert that we got the expected object)

A producer scenario where a object is the input for the test and the output is a byte[]:
IPublisher --> message (as object) --> message (deserialized) --> message (byte[]) (assert that we got the expected byte[])

**Comment by BEagle1984** [comment]
My friend, you should be able to do this already. The `IProducer` accepts any `object` as message body, including a `byte[]` and I've apparently been so smart to take this into account in the `JsonMessageSerializer`, where I avoid to try to serialize it again if it is already a byte array.
Give it a try (pseudo code here).

```c#
var byteArray = Encoding.Utf8.GetBytes(json);
var producer = broker.GetProducer(endpoint);
producer.Produce(byteArray);
```

**Comment by msallin** [comment]
Smart guy! :) It works! 

However, `message.RawContent` doesn't. It is null.
Here is what I've got now. The scenario is: Consuming a record from a topic, convert it and write it to another topic.

It's a lot of code. Do you have idea how we could simplify it? Might providing some extension methods and helpers which are only used for integration testing would be a good idea.

```
public async Task ExecuteAsync()
{
    // Arrange
    byte[] = Encoding.UTF8.GetBytes("{...}");
    using IServiceScope scope = _webApplicationFactory.Services.CreateScope();
    var broker = scope.ServiceProvider.GetRequiredService<IBroker>();

    // Internal events are directly emitted to the bus.
    // Events for which an endpoint is configured are emitted as IOutboundMessage<T> to the bus.
    IList<IOutboundMessage<MyRecord>> externalEvents = new List<IOutboundMessage<MyRecord>>();
    scope.ServiceProvider.GetRequiredService<BusConfigurator>()
        .Subscribe<IOutboundMessage<MyRecord>>(e => externalEvents.Add(e));

    // Calling this producer is like there would be an "incoming" record from X.
    IProducer producer = broker.GetProducer(new KafkaProducerEndpoint("Topic1"));

    // Act
    await producer.ProduceAsync(recordBytes);

    // Assert
    externalEvents.Count.Should().Be(1);
    IOutboundMessage<MyRecord> message = externalEvents.Single();
    message.Endpoint.Name.Should().Be("Topic2");
    string jsonMessage = Encoding.UTF8.GetString(message.RawContent);

    const string expectedMessage = "{....}";
    Assert.Equal(expectedMessage, jsonMessage);
}
```

**Comment by BEagle1984** [comment]
> However, message.RawContent doesn't. It is null.

That's a design flaw, my bad. I will fix that. The `IOutboundMessage` you subscribe is not the one that has been created/enriched by the `Producer` so it lacks and raw body and potentially some headers (especially the ones added by the `JsonMessageSerializer`, obviously).

**Comment by BEagle1984** [comment]
Forget my previous message. I just tested with the newer version and the `RawMessage` is properly set.

Note that starting from the upcoming release 2.0.0 you will have to explicitly call `PublishOutboundMessagesToInternalBus` on the `BusConfigurator` to be able to subscribe to the `IOutboundEnvelope` (formely `IOutboundMessage`).
This is because of a change I had to do to properly implement the message filters (like `KafkaGroupIdFilterAttribute`) but I'm trying to revert to the previous behavior (`PublishOutboundMessagesToInternalBus` only affects the _pure_/_unwrapped_ messages, but the `IOutboundEnvelope` can always be subscribed).

**Comment by BEagle1984** [comment]
@msallin can you confirm whether there is an issue or not? Is the stuff working as expected? (beside it being verbose)

**Comment by msallin** [comment]
I tested it. It works as expected. I didn't change anything on the BusConfigurator (no "PublishOutboundMessagesToInternalBus ").

About being verbose:
In our project we will heavy relay on those testing stuff. Lets collect us some experience first about what we actually need. Then we can contribute code to simplify it.
