### ISSUE TITLE
Convert KafkaStatisticsEvent to strongly typed object

### ISSUE THREAD

**Issue by meggima** [BEagle1984/silverback#68]
At the moment the `KafkaStatisticsEvent` contains only the raw JSON as string.
It would be useful to convert that JSON into a strongly typed Dto.

I already created the necessary C# classes with correct Attributes for the JSON field mapping in one of my projects. I could share this work with you if you want.

**Comment by BEagle1984** [comment]
@meggima don't be shy, add the code yourself and drop me a pull request. That would be amazing! 😀
