### ISSUE TITLE
Supporting Avro

### ISSUE THREAD

**Issue by alefcarlos** [BEagle1984/silverback#75]
Hi! This lib is awesome, thank you ! ;)

Is there a way to support Avro in Kafka?

**Comment by BEagle1984** [comment]
Hi, Avro isn't currently supported by Silverback. It's something I will definitely have a look into in the future but it has never been a priority so far.
I don't have experience with it, since we don't use it (yet) in the company I work for and I'm therefore unsure about a proper and ergonomic way to integrate it into Silverback.
Do you have any idea how the API may look like? Consuming should be pretty straightforward and transparent but how do you expect to produce an Avro record? I would definitely like to have a mechanism to map the POCO message model (`IMessage`) to the Avro GenericRecord automatically. Do you have any idea/suggestion? I'm in that case more than happy to look into it and see if I can integrate it.

**Comment by BEagle1984** [comment]
Sorry @alefcarlos. I just had a quick look into the documentation and it looks like it could be quite easier. Using `avrogen` you can already generate c# classes for the messages and the provided `AvroSerializer` will handle them transparently.

I will have deeper look into it and build a small prototype.

I'll write an update on this matter asap.

**Comment by alefcarlos** [comment]
I'm trying to integrate Silverback with Kafka JDBC Sink, but it expects schema info and payload, for example:

```
schema: {...},
payload: {...}
```

And using JsonSerializer is quite difficult to manage this. Have you already integrated Silverback with JDBC Sink using JsoSerializer ?

AvroSerializer would made the magic

**Comment by BEagle1984** [comment]
No, I never used the JDBC sink.

But, good news, I will add the Avro / SchemaRegistry support in the upcoming release 2.1.
You could get a beta or release candidate version by the end of this week. Stay tuned!

**Comment by BEagle1984** [comment]
Here you go @alefcarlos. I just uploaded the pre-release 2.1.0-rc1.

A new package [`Silverback.Integration.Kafka.SchemaRegistry`](https://www.nuget.org/packages/Silverback.Integration.Kafka.SchemaRegistry/) contains an `AvroSerializer` that you can use with a schema registry, as shown in the doc here: https://beagle1984.github.io/silverback/docs/advanced/serialization#apache-avro.

(The C# message models can be generated from an Avro schema using [AvroGen](https://www.nuget.org/packages/Confluent.Apache.Avro.AvroGen/).)

Let me know if it solves your issue. :wink:

**Comment by alefcarlos** [comment]
@BEagle1984 you're awesome !

But I have a suggestion, I can't read AvroMessageSerializer from appSettings:

```json
  "Silverback": {
    "Using": [
      "Silverback.Integration.Kafka",
      "Silverback.Core.Model",
      "Silverback.Integration.Kafka.SchemaRegistry",
      "Super.GlobalPlatform.Authorizer.Intregation.Contracts"
    ],
    "Outbound": [
      {
        "MessageType": "RequestReceivedEvent",
        "Endpoint": {
          "Type": "KafkaProducerEndpoint",
          "Name": "cd-authorizer-received-requests",
          "Configuration": {
            "BootstrapServers": "PLAINTEXT://localhost:9092",
            "ClientId": "cd-ms-authorizer"
          },
          "Serializer": {
            "Type": "AvroMessageSerializer`1",
            "SchemaRegistryConfig": {
              "Url": "http://localhost:8081/"
            },
            "AvroSerializerConfig": {
              "AutoRegisterSchemas": true
            }
          }
        }
      }
    ]
  }
```

this has thrown:

```
      Application startup exception
Silverback.Messaging.Configuration.SilverbackConfigurationException: Error in Outbound configuration section. See inner exception for details.
 ---> System.ArgumentException: Cannot create an instance of Silverback.Messaging.Serialization.AvroMessageSerializer`1[TMessage] because Type.ContainsGenericParameters is true.
```

Is there a way to make it ?

**Comment by BEagle1984** [comment]
Unfortunately not. I currently don't support generic types in the JSON configuration. I suggest you to resort to the regular fluent configuration and store only the variable parameters in your app.settings (e.g. bootstrap server and schema registry URL).

I created the issue #77 for this matter but I honestly don't guarantee that I'll go over this immediately, if ever.

**Comment by alefcarlos** [comment]
No problem ! I appreciate your enthusiasm. I'm using silverback a lot in my company. Thank you for this feature. I'm gonna use fluent configuration.
