### ISSUE TITLE
Improve logging (use structured & eventIds)

### ISSUE THREAD

**Issue by msallin** [BEagle1984/silverback#76]
That one can make use of powerful log-aggregation tools like Splunk, it is very helpful to get structured log messages.

Here is an example of a log-message which isn't structured:
https://github.com/BEagle1984/silverback/blob/7e1d3fd96333f0c84ef65cd861f4340110afd5dc/src/Silverback.Integration/Messaging/Messages/MessageLogger.cs#L131

If I want to get out the count, I've to use regex. Logging it like this:
_logger.LogInformation("Processing the batch of {count} inbound messages.", {envelopes.Count});
Will (if one uses a corresponding logging framework) write the value of count not only inside the message but as own property.

It gets even more useful if every log entry makes use of EventIds because now I can get the information of an specific log message. I.e. I want the 95-percentil of batche sizes.

I'm glad to invest few hours to switch all statements to structured logging, if you agree that it's desirable. Might we can think about the EventIds as well.

TODOs
- [X] Make all log messages structured.
- [X] Add EventIds for all log events.
- [X] Create a central class which holds all EventIds.
- [x] EventIds class into different classes (according the the NuGet-Package structure)
- [x] Split EventIds class into different classes (according the the NuGet-Package structure)
- [x] Adjust/improve method names and text of the log messages

**Comment by BEagle1984** [comment]
In some cases, like the one you pointed out, I deliberately decided to brutally concatenate the string. I thought that having multiple parameters called `count` in the log wouldn't be much useful, so I structured only the information i could give a meaningful name and foresee a usage (like topic names, etc.).
Nevertheless your example makes perfectly sense. I will structure everything from now on, fixing the existing stuff best-effort. Let me know if there's something you need asap (or drop a pr).

**Comment by msallin** [comment]
Maybe also consider this, for hot paths: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/loggermessage?view=aspnetcore-3.1

**Comment by BEagle1984** [comment]
Nice finding. Thanks for the hint. 👍

**Comment by msallin** [comment]
This one would be nice, if we could change it:

```
2020-03-31 13:12:19.973 loglevel="Information" sourceContext="Silverback.Messaging.ErrorHandling.ErrorPolicyHelper"  message="Processing inbound message. (Endpoint: xy, Offset: 3@5321616)" exception="" {trace_context="00-9c52d77a3fe8204fbf38ca9494de45be-6fe102a0ee05914f-00", trace_id="9c52d77a3fe8204fbf38ca9494de45be", trace_flag=None, trace_span_id="6fe102a0ee05914f", trace_operation="Silverback.Messaging.Broker.Consumer-ConsumeMessage"}
```
This will make it possible to easy get # of processed message per endpoint.

**Comment by BEagle1984** [comment]
I’m pretty sure that this one should be properly logged. That kind of messages (with the JSON-like message info appended to the end of the message) are logged via this class: src/Silverback.Integration/Messaging/Messages/MessageLogger.cs. I think I properly provide the parameter to the logger. Can you quickly double check the class I mentioned?

**Comment by BEagle1984** [comment]
@msallin I just did a test with your `AllPropertiesMessageTemplateTextFormatter` and I can confirm that this particular log entry ("Processing inbound message") is properly structured.

```
2020-04-02 20:02:41.218 loglevel="Information" message="Processing inbound message. (Endpoint: silverback-examples-events, Type: Silverback.Examples.Common.Messages.SimpleIntegrationEvent, Silverback.Examples.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null, Id: 457a0fff-dda7-496c-80cb-828ac7a89a02, Offset: 1@9)" { endpointName="silverback-examples-events", messageType="Silverback.Examples.Common.Messages.SimpleIntegrationEvent, Silverback.Examples.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", messageId="457a0fff-dda7-496c-80cb-828ac7a89a02", offset="1@9", SourceContext="Silverback.Messaging.ErrorHandling.ErrorPolicyHelper", ActivityId="00-10de4ce2c12b7747ada85e269877b6d7-f53f80f114853345-00", ParentActivityId="00-10de4ce2c12b7747ada85e269877b6d7-4af97b7b01754546-00", ActivityRootId="10de4ce2c12b7747ada85e269877b6d7" }```

**Comment by msallin** [comment]
> @msallin I just did a test with your `AllPropertiesMessageTemplateTextFormatter` and I can confirm that this particular log entry ("Processing inbound message") is properly structured.
> 
> ```
> 2020-04-02 20:02:41.218 loglevel="Information" message="Processing inbound message. (Endpoint: silverback-examples-events, Type: Silverback.Examples.Common.Messages.SimpleIntegrationEvent, Silverback.Examples.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null, Id: 457a0fff-dda7-496c-80cb-828ac7a89a02, Offset: 1@9)" { endpointName="silverback-examples-events", messageType="Silverback.Examples.Common.Messages.SimpleIntegrationEvent, Silverback.Examples.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", messageId="457a0fff-dda7-496c-80cb-828ac7a89a02", offset="1@9", SourceContext="Silverback.Messaging.ErrorHandling.ErrorPolicyHelper", ActivityId="00-10de4ce2c12b7747ada85e269877b6d7-f53f80f114853345-00", ParentActivityId="00-10de4ce2c12b7747ada85e269877b6d7-4af97b7b01754546-00", ActivityRootId="10de4ce2c12b7747ada85e269877b6d7" }```
> ```

Jep, it is. My bad, sorry...!

**Comment by msallin** [comment]
Due to our discussion, I changed the title of the ticket.
It would be great to have structured logging and EventIds everywere. Or at least for Errors and Warnings. For a streaming app Silverback is always the hot path and we are facing already the situation where we want to improve the perf of our app. Releated to this, we can also consider to transform logging into this (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/loggermessage?view=aspnetcore-3.1). Not important for startup etc but for producers and consumers.

Due to our high requirements to logging (structured & eventId) and perf (high perf logging), I will be able to invest ~1d on our next sprint.

In the mean time, lets discuss what and how it should be done.

**Comment by BEagle1984** [comment]
For the performance there may be room for quite a few improvements other than logging. I plan to work a bit on that for the release 3.0 but I gotta be careful with that. 😉

**Comment by msallin** [comment]
Oh.. I love perf stuff 😍 Let's make a workshop! 😄
