### ISSUE TITLE
Chunking: TemporaryMessageChunk has composite primary key defined with data annotations.

### ISSUE THREAD

**Issue by ppx80** [BEagle1984/silverback#78]
I configured chunking as described in the [documentation](https://beagle1984.github.io/silverback/docs/advanced/chunking), but while generating the DB migration I received the following error:

```
System.InvalidOperationException: Entity type 'TemporaryMessageChunk' has composite primary key defined with data annotations. To set composite primary key, use fluent API. 
```

To fix it in my EnityTypeConfigurator of 'TemporaryMessageChunk' I added the index configuration:

``` csharp
builder.HasKey(temporaryMessageChunk => new 
{ 
    temporaryMessageChunk.OriginalMessageId, 
    temporaryMessageChunk.ChunkId
});
```

Is this the right way?

**Comment by BEagle1984** [comment]
Yep, that's the proper way and is now documented in [Sample DbContext](https://beagle1984.github.io/silverback/docs/extra/dbcontext). Thanks!
