### ISSUE TITLE
OpenTracing integration

### ISSUE THREAD

**Issue by alefcarlos** [BEagle1984/silverback#79]
I'm writing an OpenTracing integration to Silverback in this [repo](https://github.com/alefcarlos/Silverback.Integration.OpenTracing), I think  it would be nice if this integration was bult-in.

Is Behaviors the best approach ?

**Comment by BEagle1984** [comment]
Ciao Carlos

That's amazing!

We already added support for `System.Diagnostic.Activity` and it was integrated via broker behaviors (they were actually originally created for this purpose). Have a look here:
* https://github.com/BEagle1984/silverback/blob/develop/src/Silverback.Integration/Messaging/Diagnostics/ActivityProducerBehavior.cs
* https://github.com/BEagle1984/silverback/blob/develop/src/Silverback.Integration/Messaging/Diagnostics/ActivityConsumerBehavior.cs

So yes, this is in my opinion still the way to go. 👍 


I have zero experience with OpenTracing but I know that there is a [library](https://github.com/opentracing-contrib/csharp-netcore) that would (if I understand it correctly) automatically create a span for every activity and add a logger provider to route the logged events to OpenTracing. Wouldn't this do the trick already?

**Comment by msallin** [comment]
Fyi:
OpenTracing and OpenCensus have merged to form OpenTelemetry!
OpenTelemetry will become first class support from .NET, by using the Activity-Framework:
https://medium.com/opentelemetry/opentelemetry-net-sdk-progress-3a63dcdc6cb0

**Comment by alefcarlos** [comment]
@msallin, I'm very excited about OpenTelemery, but it's under development. I wouldn't like to deploy it to production until GA.

@BEagle1984, I also like dotnet-contrib, but my experience using it was a trouble.

There's one thing  that about span context, I have created a TextMap to propagate the context between Producer and Consumer.

dotnet-contrib creates this context for http request, http-client.

**Comment by msallin** [comment]
Jep, I understand. I just want to make you aware of this, that you are able to "balance" your investments.

**Comment by alefcarlos** [comment]
@msallin, I was trying OpenTelemery a few months ago, it's incredible! Collectors work so well, it is easy to configure and maintain. .
