### ISSUE TITLE
2.1.0-rc8

### ISSUE THREAD

**Issue by 1bberto** [BEagle1984/silverback#82]
When does the release [2.1.0-rc8](https://github.com/BEagle1984/silverback/releases/tag/2.1.0-rc8) will be GA?
i'm looking to forward to use this feature!

**Comment by BEagle1984** [comment]
Ciao @1bberto, it is already available at nuget.org, as prerelease.
The stable version will be released in the next few days or weeks, depending on the feedback I get from the early adopters. 😉 It is anyway safe to use it already if you ask me (when I label the version as "release candidate" it means that it reached a usable state and I will not implement any further breaking change, just bug fixes and optimizations where needed).
