### ISSUE TITLE
Message Identifier - x-message-id

### ISSUE THREAD

**Issue by 1bberto** [BEagle1984/silverback#95]
im using the header `x-message-id` in a property in my code and its not being reflected in my event header when I publish it.

```
public class TurnoverData
{
        public Turnover Turnover { get; set; }
        public string AccountIdToBeActivated { get; set; }
}
```
```
public class Turnover
{
        [Header("x-message-id")]
        public string TurnoverId { get; set; }
        public string CreationDateTime { get; set; }
        public string PostingDate { get; set; }
}
```

I check the source code and found that just if the property is called `Id` or `MessageId` the lib retrieve the value and put it in the headers

**Comment by BEagle1984** [comment]
Which version are you using?

**Comment by 1bberto** [comment]
im currently using the version 2.1.1

**Comment by BEagle1984** [comment]
Is `TurnoverData` the message being published? If so, the `HeaderAttribute` is currently supported only on the properties in the root object.

**Comment by 1bberto** [comment]
yes it is, TurnoverData is the root object.
It there a chance to change this to search in the whole object structure for the `HeaderAttribute `?

**Comment by BEagle1984** [comment]
Not out of the box. It involves reflection and I kept the logic as lean as possible. The attributes are also being cached and allowing them in a child object would increase the complexity (considering polymorphism as well).

You got many workarounds tho:
1. Move the property to the root
1. Have a calculated property in the root that reflects the value of the child property and decorate that one with the attribute
1. Write a behavior that sets your header (you don’t need to use reflection, just car to your message type and set the header from the property)
1. Replace the `HeadersWriterProducerBehavior` with a custom implementation

I would go with option 1. If that’s not possible 3 is my second choice.

**Comment by 1bberto** [comment]
I've thought about the third option too.
I though that maybe there would exist another way to do it without having to create a Behavior, but well, i know that reflection is painfull and it carries other issues with that also. 
Thanks a lot @BEagle1984 for the quickly replies!
