### ISSUE TITLE
One topic with multiple message types

### ISSUE THREAD

**Issue by 1bberto** [BEagle1984/silverback#98]
It is possible to have a unique topic to store more than one event type (type A and type B for example)? 
If so, can I create multiple subscribers to manage it, one for the type A and other for type B to the same topic?

**Comment by BEagle1984** [comment]
Yes, sure.

If you use Silverback both to produce and consume into that topic it works out-of-the-box. The default `JsonMessageSerializer` will rely on an header (`x-message-type`) that contains the fully qualified name of the message model and allows therefore to properly resolve and deserialize it on the consumer side.

Then you can have as many subscribers as you want and the only discriminator is the type of the message that as to be compatible (yes, you can catch base types or even have a subscriber to `object`, that would catch all messages of any type, being those coming from a topic or an internal publisher).

See also the [Serialization](https://beagle1984.github.io/silverback/docs/advanced/serialization) documentation for further possibilities.
